use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    emit_data_includes();
}

// Enumerates JSON files in src/data/{items,gems,runes,skills,classes}/ plus the
// top-level singletons (affixes, sets, runewords, …) and emits
// `$OUT_DIR/data_includes.rs` with `include_str!` macros for each. The calc
// layer's `data.rs` includes that file to pull every JSON into the compiled
// binary — no runtime filesystem access required.
fn emit_data_includes() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let data_root = Path::new(&manifest_dir).join("..").join("src").join("data");
    let data_root = data_root
        .canonicalize()
        .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", data_root.display()));

    let mut out = String::new();
    out.push_str("// Auto-generated by src-tauri/build.rs — do not edit.\n\n");

    let singletons: &[(&str, &str)] = &[
        ("AFFIXES_JSON", "affixes.json"),
        ("AUGMENTS_JSON", "augments.json"),
        ("CRYSTALS_JSON", "crystals.json"),
        ("GAME_CONFIG_JSON", "game-config.json"),
        ("ITEM_GRANTED_SKILLS_JSON", "item-granted-skills.json"),
        ("RUNEWORDS_JSON", "runewords.json"),
        ("SETS_JSON", "sets.json"),
        ("TREE_NODES_JSON", "tree-nodes.json"),
    ];
    for (name, file) in singletons {
        let path = data_root.join(file);
        let canonical = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", path.display()));
        out.push_str(&format!(
            "pub const {}: &str = include_str!({:?});\n",
            name, canonical
        ));
        println!("cargo:rerun-if-changed={}", canonical.display());
    }

    let categories: &[(&str, &str)] = &[
        ("CLASSES_JSON", "classes"),
        ("GEMS_JSON", "gems"),
        ("ITEMS_JSON", "items"),
        ("RUNES_JSON", "runes"),
        ("SKILLS_JSON", "skills"),
    ];
    for (const_name, dir) in categories {
        let dir_path = data_root.join(dir);
        let mut files: Vec<PathBuf> = fs::read_dir(&dir_path)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", dir_path.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
            .collect();
        files.sort();

        out.push_str(&format!("\npub const {}: &[&str] = &[\n", const_name));
        for f in &files {
            let canonical = f
                .canonicalize()
                .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
            out.push_str(&format!("    include_str!({:?}),\n", canonical));
            println!("cargo:rerun-if-changed={}", canonical.display());
        }
        out.push_str("];\n");
        println!("cargo:rerun-if-changed={}", dir_path.display());
    }

    let dest = Path::new(&out_dir).join("data_includes.rs");
    fs::write(&dest, out).expect("failed to write data_includes.rs");
}
